apiVersion: v1
kind: Service
metadata:
  name: pensgame
  labels:
    app.kubernetes.io/name: pensgame
    app.kubernetes.io/part-of: pensgame
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pensgame
    app.kubernetes.io/part-of: pensgame
  ports:
    - name: http
      port: 80
      targetPort: 3000
