apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pensgame
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/pensgame
    newName: registry.144.91.77.245.sslip.io/pensgame
    newTag: 4f14e4ed46f6955e643ceca637f79a1065decb56
